version: "3"

services:
  registry:
    image: registry:2
    restart: always
    volumes:
      - ./data:/var/lib/registry
    ports:
      - 35000:5000
    networks:
      - registry-network

  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports:
      - 35080:80
    networks:
      - registry-network

networks:
  registry-network:

